### ISSUE TITLE
403 Response

### ISSUE THREAD

**Issue by tjuzdy** [dynomake/libretranslate-java#12]
I test it as follows,but get 403 response,what parameters are missing

Translator.setUrlApi("https://libretranslate.com/translate");
System.out.println(Translator.translate(Language.RUSSIAN, Language.CHINESE, "Для примера, переведем текст с русского на английский и выведем в консоль:"));

Kind regards

**Comment by dynomake** [comment]
Hi. Its because of libretranslate.com requires api key.

```java
Translator.setApiKey("your_api_key");
```
