### ISSUE TITLE
Problem to import dependency in maven

### ISSUE THREAD

**Issue by joseph7744** [dynomake/libretranslate-java#13]
![Captura de tela 2024-08-09 104803](https://github.com/user-attachments/assets/91dbd7b5-dd1f-4a9f-b3ab-dee828b9f45d)

**Comment by dynomake** [comment]
Sorry for it, try it now

**Comment by FelixBrs** [comment]
still have the same problem

**Comment by dynomake** [comment]
what about now? maybe you need to invalidate old cache of my maven repository?

you can check it out here, it works https://maven.dynomake.space/

**Comment by dynomake** [comment]
so if you still have this trouble, you can compile it as jar (or i can send you a jar) and add jaf-file as depend
