### ISSUE TITLE
Can't import the Translator class

### ISSUE THREAD

**Issue by fnzainal** [dynomake/libretranslate-java#8]
I've tried to use this library on DFM  but can't import the class, have try to clean and rebuild, even I restart the Android studio.
note: there is suggestion Translate from Mlkit because I added it on base module

How to fix this?
![bug-translate](https://github.com/suuft/libretranslate-java/assets/13946213/3caa9e79-11c9-4ed4-9fae-687c8dff5595)

**Comment by suuft** [comment]
This has never happened before. There is a dependency in the repository, maybe IDE didnt load it?
