### ISSUE TITLE
Error on Language.valueOf("code")

### ISSUE THREAD

**Issue by N7ghtm4r3** [dynomake/libretranslate-java#9]
When invoked the Language.valueOf("code") method is thrown

**java.lang.IllegalArgumentException: No enum constant net.suuft.libretranslate.Language.it
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at net.suuft.libretranslate.Language.valueOf(Language.java:8)**

**Comment by dynomake** [comment]
Sorry for long answer. Its because you should use:

```java
Language.fromCode("code");
```

**Comment by N7ghtm4r3** [comment]
Thank you!
